server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # <hostname>:<port>/<database> needs to be filled in
    url: jdbc:mysql://<hostname>:<port>/<database>?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Australia/Sydney
    username: # needs to be filled in
    password: # needs to be filled in
    hikari:
      connection-test-query: SELECT 1 # Automatic connection detection
      connection-timeout: 60000 # The database connection timeout period is 30 seconds by default
      idle-timeout: 500000 # The maximum survival time of idle connections
      max-lifetime: 540000 # Control the longest lifetime of connections in the pool
      maximum-pool-size: 12 # Maximum number of connections in the connection pool
      minimum-idle: 10 # Minimum number of idle connections
      pool-name: SPHHikariPool # Connection pool name
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# It is used to print the sql statements generated by the framework for easy debugging
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl