server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # <hostname>:<port>/<database> needs to be filled in
    url: jdbc:mysql://<hostname>:<port>/<database>?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Australia/Sydney
    username: # needs to be filled in
    password: # needs to be filled in
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Australia/Sydney
  data:
    redis:
      host: 192.168.230.101
      port: 6379
      database: 0
      password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true
